$id#: https://amdocs.com/schemas/nef/Role.json
$schema: http://json-schema.org/draft-07/schema
NAME: Role
description: No Description for Role
example: Role
name: Role
properties:
    RoleDescription:
        description: Role Description
        example: RoleDescription
        format: ''
        mandatory: y
        name: RoleDescription
        pattern: ''
        precision: '0'
        type: string
    RoleName:
        description: User Role
        example: RoleName
        format: ''
        mandatory: y
        name: RoleName
        pattern: ''
        precision: '0'
        type: string
    RoleValue:
        description: Role Value
        example: RoleValue
        format: ''
        mandatory: y
        name: RoleValue
        pattern: ''
        precision: '0'
        type: string
    id:
        description: Enter Description Here
        example: id
        format: ''
        mandatory: n
        name: id
        pattern: ''
        precision: '0'
        type: string
required:
- RoleName
- RoleValue
- RoleDescription
title: Schema for Role
type: object
