$defs:
    API_Consumers:
        NAME: API_Consumers
        description: No Description for API Consumers
        example: API_Consumers
        name: API_Consumers
        properties:
            ConsumerName:
                description: No Description for ConsumerName
                example: ConsumerName
                format: ''
                mandatory: y
                name: ConsumerName
                pattern: ''
                precision: '0'
                type: string
            Contact_Details:
                description: No Description for Contact Details
                example: Contact_Details
                format: ''
                mandatory: y
                name: Contact_Details
                pattern: ''
                precision: '0'
                type: string
            NEF_Credentials:
                description: 'No Description for NEF Credentials '
                example: NEF_Credentials
                format: ''
                mandatory: y
                name: NEF_Credentials
                pattern: ''
                precision: '0'
                type: string
        required:
        - ConsumerName
        - Contact_Details
        - NEF_Credentials
        type: object
$id#: https://amdocs.com/schemas/nef/Service.json
$schema: http://json-schema.org/draft-07/schema
NAME: Service
description: 'Provides Access to '
example: Service
mandatory: y
name: Organization_-_Services_AF_API_Consumers
properties:
    API_Consumers:
        $ref: '#/$defs/API_Consumers'
        description: 'Provides Access to '
    API_Subscription:
        $ref: '#/components/schemas/API_Subscription'
        $ref#: NEF_ApplicationUserProfile_DataModel_API_Subscription_Schema.json
        cardinality: OneToOne
        description: Subscribe to Use
        mandatory: y
        name: Organization_-_Services_API_Set
        type: string
    Industry:
        description: No Description for Industry
        example: Industry
        format: ''
        mandatory: y
        name: Industry
        pattern: ''
        precision: '0'
        type: string
    Name:
        description: No Description for Name
        example: Name
        format: ''
        mandatory: y
        name: Name
        pattern: ''
        precision: '0'
        type: string
    UseCase:
        description: No Description for UseCase
        example: UseCase
        format: ''
        mandatory: y
        name: UseCase
        pattern: ''
        precision: '0'
        type: string
    VolumeOrg:
        description: No Description for VolumeOrg
        example: VolumeOrg
        format: ''
        mandatory: n
        name: VolumeOrg
        pattern: ''
        precision: '0'
        type: string
    id:
        description: Enter Description Here
        example: id
        format: ''
        mandatory: n
        name: id
        pattern: ''
        precision: '0'
        type: string
required:
- Name
- Industry
- UseCase
title: Schema for Service
type: object
