$id#: https://amdocs.com/schemas/nef/Contact.json
$schema: http://json-schema.org/draft-07/schema
NAME: Contact
description: Contact and Credential Details
example: Contact
name: Contact
properties:
    Role:
        $ref#: NEF_ApplicationUserProfile_DataModel_Role_Schema.json
        cardinality: OneToOne
        description: 'Has role '
        mandatory: y
        name: Contact_v
        type: string
    UserCreationDate:
        description: User creation date.
        example: UserCreationDate
        format: ''
        mandatory: y
        name: UserCreationDate
        pattern: ''
        precision: '0'
        type: string
    UserEmail:
        description: User Email
        example: UserEmail
        format: ''
        mandatory: y
        name: UserEmail
        pattern: ''
        precision: '0'
        type: string
    UserFirstName:
        description: User Firstname
        example: UserFirstName
        format: ''
        mandatory: y
        name: UserFirstName
        pattern: ''
        precision: '0'
        type: string
    UserJobRole:
        description: User Job Role
        example: UserJobRole
        format: ''
        mandatory: y
        name: UserJobRole
        pattern: ''
        precision: '0'
        type: string
    UserLastLoginDate:
        description: User last login date.
        example: UserLastLoginDate
        format: ''
        mandatory: y
        name: UserLastLoginDate
        pattern: ''
        precision: '0'
        type: string
    UserModificationDate:
        description: User modification date.
        example: UserModificationDate
        format: ''
        mandatory: y
        name: UserModificationDate
        pattern: ''
        precision: '0'
        type: string
    UserName:
        description: User Name
        example: UserName
        format: ''
        mandatory: y
        name: UserName
        pattern: ''
        precision: '0'
        type: string
    UserPassword:
        description: User Password
        example: UserPassword
        format: ''
        mandatory: y
        name: UserPassword
        pattern: ''
        precision: '0'
        type: string
    UserPhoneNumber:
        description: User Phone Number
        example: UserPhoneNumber
        format: ''
        mandatory: y
        name: UserPhoneNumber
        pattern: ''
        precision: '0'
        type: string
    UserPicture:
        description: User Picture
        example: UserPicture
        format: ''
        mandatory: y
        name: UserPicture
        pattern: ''
        precision: '0'
        type: string
    UserState:
        description: User State
        example: UserState
        format: ''
        mandatory: y
        name: UserState
        pattern: ''
        precision: '0'
        type: string
    UserTermOfUseDate:
        description: The date the user has agreed on Term of use.
        example: UserTermOfUseDate
        format: ''
        mandatory: y
        name: UserTermOfUseDate
        pattern: ''
        precision: '0'
        type: string
    id:
        description: Enter Description Here
        example: id
        format: ''
        mandatory: n
        name: id
        pattern: ''
        precision: '0'
        type: string
required:
- UserEmail
- UserName
- UserFirstName
- UserPicture
- UserPhoneNumber
- UserJobRole
- UserPassword
- UserState
- UserCreationDate
- UserModificationDate
- UserLastLoginDate
- UserTermOfUseDate
title: Schema for Contact
type: object
